---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@c97ca7c448df211268616ce438777228fe103733 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lychee-args:
            --exclude 'https://scholar.google.com/citations\?user=.*'
            --no-progress --verbose .
