---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@0865144b6fdb1eb6b77f4033f72fb5239d1ba44f # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
