name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
