---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@9d6e96a69f2f213846703cbc4bd7ad067366fcaf # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
