name: Update README

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1-5"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Autogenerate README
        # yamllint disable-line rule:line-length
        uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948 # v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.README_SCRIBE }}
        with:
          template: templates/README.md.tpl
          writeTo: README.md

      - name: Push README to main
        # yamllint disable-line rule:line-length
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          commit_message: Update generated README
