---
name: Update README

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  schedule:
    - cron: 0 9 * * *
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate token
        id: generate-token
        # yamllint disable-line rule:line-length
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ vars.README_APP_ID }}
          private-key: ${{ secrets.README_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Find the last commit to README
        id: commit-count
        run: >-
          echo count="$(git log --oneline --since=midnight main -- ./README.md |
          wc -l)" >> "$GITHUB_OUTPUT"

      - name: Autogenerate README
        if: ${{ steps.commit-count.outputs.count == 0 }}
        # yamllint disable-line rule:line-length
        uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948 # v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.README_SCRIBE }}
        with:
          template: ./templates/README.md.tpl
          writeTo: ./README.md

      - name: Push README to main
        if: >-
          ${{ steps.commit-count.outputs.count == 0 && github.ref ==
          'refs/heads/main' }}
        # yamllint disable-line rule:line-length
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          branch: main
          commit_message: Update generated README
          commit_author: readme-scribe 🤖 <actions@github.com>
          commit_user_email: actions@github.com
          commit_user_name: readme-scribe 🤖
