---
name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 9 * * 1-5

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Find the last commit to README
        id: commit-count
        run: >-
          echo count=$(git log --oneline --since=midnight main -- ./README.md |
          wc -l) >> $GITHUB_OUTPUT

      - name: Autogenerate README
        if: ${{ steps.commit-count.outputs.count == 0 }}
        # yamllint disable-line rule:line-length
        uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948 # v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.README_SCRIBE }}
        with:
          template: ./templates/README.md.tpl
          writeTo: ./README.md

      - name: Push README to main
        if: ${{ steps.commit-count.outputs.count == 0 }}
        # yamllint disable-line rule:line-length
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          commit_message: Update generated README
